### ISSUE TITLE
Time/Day Updating

### ISSUE THREAD

**Issue by TomEagle** [gios-asu/apiarium-wp-plugin#38]
How do I get the [display-calendar] time/day to update in real-time?

**Comment by idmontie** [comment]
My guess is this and issue #39 are related. I'm guessing that for whatever reason jQuery is not being loaded in. It might be that we rely on the theme including it. I will look in to it.

**Comment by idmontie** [comment]
Twitter Bootstrap being enqueued in the theme is another undocumented dependency.
