### ISSUE TITLE
Slidder Height/Rows and Center Header

### ISSUE THREAD

**Issue by TomEagle** [gios-asu/apiarium-wp-plugin#42]
I had to add HEADER HTML below slider to get more than one line to display:
[display-column size=5]
[display-flex size=6]
<h1>_____ F I R S T __ N E W S_____</h1>
[display-slider layout=newspaper content="heading,caption"]
http://kiosk.fpcls.org/category/announcements/feed
http://kiosk.fpcls.org/category/session/feed
http://kiosk.fpcls.org/category/youth/feed
http://kiosk.fpcls.org/category/hospitality/feed
http://kiosk.fpcls.org/category/worship/feed
http://kiosk.fpcls.org/category/mission/feed
http://kiosk.fpcls.org/category/men/feed
http://kiosk.fpcls.org/category/women/feed
[/display-slider]
HEADER HTML
HEADER HTML
HEADER HTML
[/display-flex]
[/display-column]
See http://kiosk.fpcls.org/kiosk/

**Comment by idmontie** [comment]
What is the question?

**Comment by TomEagle** [comment]
![slider](https://cloud.githubusercontent.com/assets/7925995/12988344/e8b21cde-d0c5-11e5-9d74-1141f6b59861.jpg)

**Comment by TomEagle** [comment]
Without the three Headers line I originally got this to slide in.
![without_three_header_lines](https://cloud.githubusercontent.com/assets/7925995/12988631/2c09367e-d0c7-11e5-97ae-d7de5219aeed.jpg)

**Comment by idmontie** [comment]
You can center text using HTML and CSS just as you normally would, that is not part of the Apiarium plugin.

It is unclear what you mean by "header lines". The plugin will only pull the first section of text from each post as the caption.

**Comment by idmontie** [comment]
This is due your use of flex boxes. Adding the additional empty `<h3>`s just makes the box take up more room vertically, allowing more lines to display.

Working as intended.
