### ISSUE TITLE
Only First Twitter Feed Slides

### ISSUE THREAD

**Issue by TomEagle** [gios-asu/apiarium-wp-plugin#43]
See http://kiosk.fpcls.org/kiosk/

**Comment by idmontie** [comment]
Please describe what is currently happening and what you expect to happen.

**Comment by TomEagle** [comment]
I have the following shortcuts:
[display-column size=3]
[display-flex size=3]
<h2>Twitter @fpclsyouth</h2>
[display-twitter screenname="fpclsyouth"]              <-----This is the only Twitter feed that scrolls
[/display-flex]
[/display-column]
[display-column size=3]
[display-flex size=3]
<h2>Twitter @fpcls</h2>
[display-twitter screenname="fpcls"]
[/display-flex]
[/display-column]
[display-column size=3]
[display-flex size=3]
<h2>Twitter @fpclsmusic</h2>
[display-twitter screenname="fpclsmusic"]
[/display-flex]
[/display-column]

![twitter scrolls](https://cloud.githubusercontent.com/assets/7925995/12987939/fcacdffa-d0c3-11e5-8deb-d16179ba62a0.jpg)

**Comment by idmontie** [comment]
Relevant code: https://github.com/gios-asu/apiarium-wp-plugin/blob/develop/public/javascripts/main.js#L55

Most likely need to change to something like:

```
$( '.apiarium__tweet' ).parent().each(function (_, tweetContainer) {
  tweetContainer.find('.apiarium__tweet').first()
//...
```

**Comment by TomEagle** [comment]
Is this something you are looking into?
or
Is only one twitter feed going to be allowed?

**Comment by idmontie** [comment]
This has been completed and pulled into master.

**Comment by TomEagle** [comment]
Congratulations! You have fixed this one. Thank you very much.
I hope I am being helpful and not being a pain.
