### ISSUE TITLE
Only One Slider Allowed?

### ISSUE THREAD

**Issue by TomEagle** [gios-asu/apiarium-wp-plugin#44]
I have two Sliders:
#1 Slider has one feed
#2 Slidef has eight feeds
All nine feeds show up in the second (#2) Slider

**Comment by idmontie** [comment]
Please post your exact page markup to help diagnose the problem. Have you properly closed out the slider shortcodes?

Also, please wrap your markup using Markdown syntax:

\```
Like this
```

**Comment by TomEagle** [comment]
... [display-column size=5]
... [display-flex size=2]
... [display-slider content="heading,image"]
... http://kiosk.fpcls.org/category/photos/feed
... [/display-slider]
... [/display-flex]
... [/display-column]
... 
... [display-column size=5]
... [display-flex size=6]
... <h1>_____ F I R S T __ N E W S_____</h1>
... [display-slider layout=newspaper content="heading,caption"]
... http://kiosk.fpcls.org/category/announcements/feed
... http://kiosk.fpcls.org/category/session/feed
... http://kiosk.fpcls.org/category/youth/feed
... http://kiosk.fpcls.org/category/hospitality/feed
... http://kiosk.fpcls.org/category/worship/feed
... http://kiosk.fpcls.org/category/mission/feed
... http://kiosk.fpcls.org/category/men/feed
... http://kiosk.fpcls.org/category/women/feed
... [/display-slider]
... <h2></<h2>
... <h2></<h2>
... <h2></<h2>
... 
... [/display-flex]
... [/display-column]

**Comment by TomEagle** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/7925995/12990438/02f77d82-d0d0-11e5-9270-c74c04288d10.jpg)

**Comment by idmontie** [comment]
I cannot reproduce this error:

```
[display theme=green]
  [display-row]
      [display-flex size=3]
        [display-slider layout=newspaper content="heading,caption"]
          https://asunow.asu.edu/feeds/sustainability 
        [/display-slider]
      [/display-flex]
      [display-flex size=3]
        [display-slider layout=newspaper content="heading,caption"]
          https://asunow.asu.edu/feeds/sustainability-asu 
        [/display-slider]
      [/display-flex]
  [/display-row]
[/display]
```

**Comment by TomEagle** [comment]
How is the best way of sliding photos that are in the wordpress media
library on my wordpress site?
Thank you so much for your help!

Tom Eagle
Dr.Tom.Eagle@gmail.com
816-524-4040 c
816-524-4041 h

**Comment by idmontie** [comment]
@TomEagle Please create a new issue for unrelated questions.
