### ISSUE TITLE
Getting ALL posts displayed, Not ONE Category

### ISSUE THREAD

**Issue by TomEagle** [gios-asu/apiarium-wp-plugin#47]
The display-slider is presenting all posts I have.  When I do the http:...., I only get the posts for the category I have specified.
![men](https://cloud.githubusercontent.com/assets/7925995/12995451/177db632-d0ed-11e5-915c-ddb8ac200529.jpg)

**Comment by TomEagle** [comment]
![men-script](https://cloud.githubusercontent.com/assets/7925995/12995601/2b3618c6-d0ee-11e5-9e06-7b25976dde50.jpg)

**Comment by idmontie** [comment]
I'm not quite sure what you mean?

> When I do the http:...., I only get the posts for the category I have specified.

Yes that is how it is intended to work.

> The display-slider is presenting all posts I have.

When does this happen then? If you are specifying a category and it displays those posts in that category, then when does it actually present all of the posts?

**Comment by TomEagle** [comment]
Are you striping the category out of the URL when you clean?

When I specify a category, it display ALL posts, NOT just the posts with the specified category.

**Comment by TomEagle** [comment]
Display-slider is displaying ALL POSTS from the Wordpress site even when I
specify one category.

If I manually put the URL in a browser, I get only the post(s) from that
category only. (Which is the jpg I included.

Tom Eagle
Dr.Tom.Eagle@gmail.com
816-524-4040 c
816-524-4041 h

**Comment by idmontie** [comment]
We don't do anything special to the URLs except check that they are not relative to the WordPress site. 

Most likely this is a bug in WordPress, since all this plugin will do is call the Simple Pie XML parser, which will ask for the given URL contents and will cache those contents.

Unable to reproduce this on our two different installations of this plugin that pull in WordPress category feeds.

**Comment by TomEagle** [comment]
Did you try the following this feed in your installations?
http://kiosk.fpcls.org/category/men/feed/
Look at the following and see what I am viewing:
http://kiosk.fpcls.org/kiosk/
I see All the post, not just the category of men.
There should be only one post shown.
I have tried different XML viewers of the feed and only get one post.
I have used http://codebeautify.org/xmlviewer with the URL of the above feed and only get one post.
I don't think the multiple post are coming from wordpress if the URL feed is used.

**Comment by idmontie** [comment]
Do you experience the same issue when using different categories? Or just that one feed?

**Comment by TomEagle** [comment]
I changed to another post which also has one post ;
http://kiosk.fpcls.org/category/session/feed
with the same results.
The following feed of a category which doesn't have any posts:
http://kiosk.fpcls.org/category/women/feed
with the same results ... all post are displayed.

**Comment by idmontie** [comment]
Tested locally and was unable to reproduce what you are seeing:

Using http://kiosk.fpcls.org/category/session/feed

- Expected: 1 slide
- Observed: 1 slide
- Markup:

```
[display theme=green]
  [display-row]
    [display-column size=1]
      [display-flex size=1 classes=apiarium__no-border]
        [display-slider]
          http://kiosk.fpcls.org/category/session/feed
        [/display-slider]
      [/display-flex]
    [/display-column]
  [/display-row]
[/display]
```

Using http://kiosk.fpcls.org/category/women/feed:

- Expected: 0 slides
- Observed: 0 slides
- Markup:

```
[display theme=green]
  [display-row]
    [display-column size=1]
      [display-flex size=1 classes=apiarium__no-border]
        [display-slider]
          http://kiosk.fpcls.org/category/women/feed
        [/display-slider]
      [/display-flex]
    [/display-column]
  [/display-row]
[/display]
```

**Comment by TomEagle** [comment]
I am using PHP56. Wonder if that could be the problem.

**Comment by TomEagle** [comment]
I replaced on the shortcodes with the first one (men) and still get all posts.
